USE [master]
GO
/****** Object:  Database [OMS]    Script Date: 12/5/2023 7:13:14 PM ******/
CREATE DATABASE [OMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\OMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\OMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OMS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [OMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OMS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OMS] SET RECOVERY FULL 
GO
ALTER DATABASE [OMS] SET  MULTI_USER 
GO
ALTER DATABASE [OMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OMS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'OMS', N'ON'
GO
ALTER DATABASE [OMS] SET QUERY_STORE = OFF
GO
USE [OMS]
GO
/****** Object:  Table [dbo].[Agent]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Agent](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Agent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DelayReport]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DelayReport](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[AgentId] [int] NULL,
	[DelayTime] [datetime] NOT NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_DelayReport] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreatedTime] [datetime] NOT NULL,
	[DeliveredTime] [datetime] NOT NULL,
	[VendorId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[DeliveredAt] [datetime] NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trip]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trip](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_Trip] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vendor]    Script Date: 12/5/2023 7:13:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vendor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DelayReport]  WITH CHECK ADD  CONSTRAINT [FK_DelayReport_Agent] FOREIGN KEY([AgentId])
REFERENCES [dbo].[Agent] ([Id])
GO
ALTER TABLE [dbo].[DelayReport] CHECK CONSTRAINT [FK_DelayReport_Agent]
GO
ALTER TABLE [dbo].[DelayReport]  WITH CHECK ADD  CONSTRAINT [FK_DelayReport_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[DelayReport] CHECK CONSTRAINT [FK_DelayReport_Order]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Customer]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Vendor] FOREIGN KEY([VendorId])
REFERENCES [dbo].[Vendor] ([Id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Vendor]
GO
ALTER TABLE [dbo].[Trip]  WITH CHECK ADD  CONSTRAINT [FK_Trip_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[Trip] CHECK CONSTRAINT [FK_Trip_Order]
GO
USE [master]
GO
ALTER DATABASE [OMS] SET  READ_WRITE 
GO
